name: Deploy Airflow to EC2

on:
  pull_request:
    branches:
      - main
    types: [closed]

  workflow_dispatch:

env:
  AWS_REGION: us-east-1

jobs:
  deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: 📥 Checkout do Código
        uses: actions/checkout@v4

      - name: 🔐 Configurar Credenciais da AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: 🔍 Verificar Status da EC2
        id: check-status
        run: |
          STATE=$(aws ec2 describe-instances \
            --instance-ids ${{ secrets.EC2_INSTANCE_ID }} \
            --query 'Reservations[0].Instances[0].State.Name' \
            --output text)
          echo "Status atual da instância: $STATE"
          echo "INSTANCE_STATE=$STATE" >> $GITHUB_ENV

      - name: 🚀 Ligar Instância (Apenas se estiver desligada)
        if: env.INSTANCE_STATE != 'running'
        run: |
          aws ec2 start-instances --instance-ids ${{ secrets.EC2_INSTANCE_ID }}
          echo "Aguardando a instância inicializar..."
          aws ec2 wait instance-running --instance-ids ${{ secrets.EC2_INSTANCE_ID }}

      - name: 🔎 Obter IP Público Dinâmico
        id: get-ip
        run: |
          PUBLIC_IP=$(aws ec2 describe-instances \
            --instance-ids ${{ secrets.EC2_INSTANCE_ID }} \
            --query 'Reservations[0].Instances[0].PublicIpAddress' \
            --output text)
          echo "IP capturado: $PUBLIC_IP"
          echo "EC2_PUBLIC_IP=$PUBLIC_IP" >> $GITHUB_ENV

      - name: ⏳ Aguardar boot do SSH
        if: env.INSTANCE_STATE != 'running'
        run: sleep 30

      - name: ⚙️ Executar Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ env.EC2_PUBLIC_IP }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            PROJECT_DIR="/home/${{ secrets.SSH_USER }}/market_data_lakehouse"

            if [ ! -d "$PROJECT_DIR/.git" ]; then
              echo "Pasta não encontrada ou corrompida. Clonando..."
              sudo rm -rf $PROJECT_DIR
              git clone https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git $PROJECT_DIR
            fi

            cd $PROJECT_DIR
            echo "Atualizando código da branch main..."
            git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
            git fetch origin main
            git reset --hard origin/main
            git clean -fd

            echo "Configurando permissões do Airflow para o usuário do host..."
            echo -e "AIRFLOW_UID=$(id -u)" > .env
            mkdir -p ./dags ./logs ./plugins ./config

            echo "Ajustando posse dos arquivos legados..."
            sudo chown -R $USER:$USER $PROJECT_DIR

            echo "Gerando arquivo .env..."
            cat <<EOT > .env
            AIRFLOW_UID=$(id -u)
            AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
            AWS_REGION=${{ env.AWS_REGION }}
            EOT

            docker image prune -f

            echo "Subindo containers..."
            docker compose down --remove-orphans
            docker compose up airflow-init
            docker compose up -d

      - name: 🛑 Desligar Instância (Apenas se a esteira ligou a máquina)
        if: always() && env.INSTANCE_STATE != 'running'
        run: |
          aws ec2 stop-instances --instance-ids ${{ secrets.EC2_INSTANCE_ID }}
          echo "A máquina foi desligada automaticamente."
